SONARIAC-1497 Extract Analyzer to SingleFileAnalyzer class and create a new class CrossFileAnalyzer
SonarSource/sonar-iac pull request #1374
Opened 2024-06-19 09:17 UTC by rudy-regazzoni-sonarsource

2024-06-19 15:03 UTC, mstachniuk requested changes
Good progress and please see my implementation suggestion

2024-06-20 07:15 UTC, rudy-regazzoni-sonarsource commented on iac-common/src/main/java/org/sonar/iac/common/extension/analyzer/AbstractAnalyzer.java
> +  protected final String repositoryKey;
I adapted a bit a also moved the generic parsing error log to `AbstractAnalyzer`, so now it make sense to keep the `repositoryKey` here (and to set it back to `private`).

2024-06-20 09:41 UTC, mstachniuk approved these changes
LGTM and please see a small my comment

2024-06-20 09:41 UTC, mstachniuk commented on iac-common/src/main/java/org/sonar/iac/common/extension/analyzer/CrossFileAnalyzer.java
> +    }
This can be extracted to the private method in CrossFileAnalyzer and then lines 89-95 can be replaced by method call.

2024-06-20 11:35 UTC, merged