SONARIAC-1529 S6865: Should not raise issue with secondary locations on other files
SonarSource/sonar-iac pull request #1408
Opened 2024-07-08 08:02 UTC by rudy-regazzoni-sonarsource

2024-07-08 10:34 UTC, mstachniuk requested changes
I would like to have the internal property for this feature. This will help us validate the impact on Peachee much more easily. 
Please also check if the feature should be disabled for all K8s/Helm rules as they may also potentially break the analysis.

2024-07-10 14:40 UTC, rudy-regazzoni-sonarsource commented
As indicated, I updated the Jira ticket and modified the PR: now we can set an option per rule to remove secondary location on other files.

2024-07-11 09:31 UTC, mstachniuk approved these changes
LGTM

2024-07-11 09:31 UTC, mstachniuk commented on iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/AutomountServiceAccountTokenCheckTest.java
> +      "AutomountServiceAccountTokenCheck/LinkedAccount/NonCompliant/SensitiveValue/linked_account_service_token.yaml");
```suggestion
      root + "linked_account_service_token.yaml");
```

2024-07-11 09:31 UTC, mstachniuk commented on iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/visitors/KubernetesChecksVisitorTest.java
> +    verify(inputFileContext, times(1)).reportIssue(RuleKey.of("testRepo", "testRule"), range, "testIssue", List.of(secondaryLocationSameFile));
Nitpik. The `verify(inputFileContext)` is an equivalent of `verify(inputFileContext, times(1))`. 
I already fixed it in my PR https://github.com/SonarSource/sonar-iac/pull/1411 , so please leave it for now.

2024-07-11 09:48 UTC, merged