SONARIAC-572 Adapt HereDocForm to the new grammar, initial change
SonarSource/sonar-iac pull request #522
Opened 2023-02-13 16:21 UTC by mstachniuk

2023-02-14 12:55 UTC, rudy-regazzoni-sonarsource requested changes
Great work ! Please see my comments, few elements to adapt.

2023-02-14 12:55 UTC, rudy-regazzoni-sonarsource commented on iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/impl/HereDocumentImpl.java
>    }
By throwing an exception in this method, it is stopping rules currently using this method from running, which prevent us from seeing what is the impact of this PR on the ruling execution.
If possible, I would recommend to have a temporarily replacement of this method content like we did for ShellForm and ExecForm, you can very probably just copy/paste the same logic there.

2023-02-15 08:15 UTC, rudy-regazzoni-sonarsource commented on iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/impl/HereDocumentImpl.java
>    }
👍 Perfectly fine, we didn't cover also as this is temp code that is soon to be removed.

2023-02-15 08:55 UTC, rudy-regazzoni-sonarsource approved these changes
LGTM !

2023-02-15 09:09 UTC, nils-werner-sonarsource reviewed
Please add a few comments to track the method which we should remove.

2023-02-15 09:09 UTC, nils-werner-sonarsource commented on iac-extensions/docker/src/main/java/org/sonar/iac/docker/utils/ArgumentUtils.java
> +  }
Please add a comment. We should remove this helper after we drop all `literals()` methods.

2023-02-15 09:09 UTC, nils-werner-sonarsource commented on iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/impl/HereDocumentImpl.java
>    public List<SyntaxToken> literals() {
A comment is missing to drop the method.

2023-02-15 09:41 UTC, merged