SONARIAC-899 Rule S6380: Authorizing anonymous access to Azure resources is security-sensitive
SonarSource/sonar-iac pull request #854
Opened 2023-07-25 14:34 UTC by petertrr

* SONARIAC-900 Web/sites
* SONARIAC-901 ApiManagement/service
* SONARIAC-902 DataFactory/factories/linkedservices
* SONARIAC-903 Storage/storageAccounts
* SONARIAC-904 Cache/redis

2023-07-26 13:11 UTC, rudy-regazzoni-sonarsource requested changes
That's a big PR, lot of good work in there but several elements need to be reworked, either here or in a separate ticket/PR.
I don't see any Bicep test case, but as you saw the only new issues that are raised in IT are for Bicep. I would recommend adding the Bicep test case in this PR.

Next time I would recommend tackling such rule implementation in smaller steps, I believe it would have several advantages here:
- less complex for the reviewer / faster review for you to get back on it
- fix / different approach that would be provided in the first review could be applied in subsequent PR
- [babystep approach](https://xtranet-sonarsource.atlassian.net/wiki/spaces/ADM/pages/541778/SonarSource+Definitions#SonarSourceDefinitions-Babystep)

Let me know if you have any questions, happy to discuss.

2023-07-26 13:11 UTC, rudy-regazzoni-sonarsource commented on iac-extensions/arm/src/test/resources/checks/ManagedIdentityCheck/Microsoft.Web_sites.json
Missing this test case, without direct parent/inner child:
```
{
  "type": "Microsoft.Web/sites/config",
  "apiVersion": "2021-02-01",
  "name": "authsettingsV2",
  "properties": {
    "globalValidation": {
      "requireAuthentication": false,
      "unauthenticatedClientAction": "AllowAnonymous"
    }
  }
},
```

2023-07-27 11:10 UTC, petertrr commented on iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/AnonymousAccessToResourceCheck.java
> +    }).orElse(true);
Clarified, indeed there should be an `OR` between these conditions

2023-07-27 11:10 UTC, petertrr commented on iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/AnonymousAccessToResourceCheck.java
> +    }
Clarified, there should be no issue if `globalValidation` is empty or absent

2023-07-28 10:02 UTC, rudy-regazzoni-sonarsource approved these changes
LGTM! Nice improvements here! Please see few additional comments.

2023-07-28 11:17 UTC, petertrr commented on iac-extensions/arm/src/test/resources/checks/AnonymousAccessToResourceCheck/Microsoft.Web_sites.bicep
I've found in [docs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/child-resource-name-type#outside-parent-resource) that

> Specify the parent property on the child with the value set to the symbolic name of the parent. With this syntax you still need to declare the full resource type...

So a consumer of `Microsoft.Web/sites/config` would still be triggered and I already have a test like this. I'll add a `parent` property though, to have a more correct example

2023-07-28 11:18 UTC, petertrr commented on iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/AnonymousAccessToResourceCheck.java
> +    register("Microsoft.Web/sites/config", AnonymousAccessToResourceCheck::checkWebSitesAuthSettings);
Good catch, I added a name check.

2023-07-28 11:22 UTC, petertrr commented on iac-extensions/arm/src/test/resources/checks/AnonymousAccessToResourceCheck/Microsoft.Web_sites.bicep
> I would add two other examples

These examples exist in JSON already. Do you think it is necessary to repeat them also for Bicep or only to cover Bicep-specific cases, like non-nested resources?

2023-07-28 11:28 UTC, rudy-regazzoni-sonarsource commented on iac-extensions/arm/src/test/resources/checks/AnonymousAccessToResourceCheck/Microsoft.Web_sites.bicep
Usually, I like to do it in both Json and Bicep.

I first do it in Bicep, then compile it into Json and put both the Bicep and Json result in test files.
This allows me to confirm that, of course, the rule check is performed as intended, but also that our ARM Json parser and Bicep parser produce the same final AST.
Doing so showed me that it's not always the case, especially with ARM Json embedded expression (`[myFunction()]` for example).

This may not make sense to do it systematically. If you think here it's redundant and don't bring much, keep it like that 👍

2023-07-28 11:30 UTC, petertrr commented on iac-extensions/arm/src/test/resources/checks/AnonymousAccessToResourceCheck/Microsoft.Web_sites.bicep
Ahh, yes, we will indeed yield a false positive on the parent resource, thinking that `authsettingsV2` doesn't exist

2023-07-28 11:58 UTC, petertrr commented on iac-extensions/arm/src/test/resources/checks/AnonymousAccessToResourceCheck/Microsoft.Web_sites.bicep
Added a test case with a note that it's a FP

2023-07-28 12:14 UTC, merged